[workspace]
members = [".", "tools/*", "tests"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
crc = "3.4.0"

[package]
name = "imdb"
version.workspace = true
edition.workspace = true
default-run = "imdb"

[dependencies]
crc.workspace = true

[[bin]]
name = "exp"
path = "src/experiments/exp.rs"
